=== Makintoshe/Web-des-Donn-es/ValidationXML_DTD_XSD/ordinateurs.dtd
<!-- DTD pour l'exercice "crÃ©er un document XML valide" -->

<!-- dÃ©finition de l'Ã©lÃ©ment racine -->
<!ELEMENT ordinateurs (ordinateur+)>

<!-- dÃ©finition de l'Ã©lÃ©ment ordinateur -->
<!ELEMENT ordinateur (description, cpu, ram, disque+)>
<!ATTLIST ordinateur 
    numero ID #REQUIRED 
    prix CDATA #IMPLIED
>

<!-- dÃ©finition de l'Ã©lÃ©ment description -->
<!ELEMENT description (#PCDATA)>
<!ATTLIST description marque CDATA #REQUIRED>

<!-- dÃ©finition de l'Ã©lÃ©ment cpu -->
<!ELEMENT cpu EMPTY>
<!ATTLIST cpu 
    marque  (intel | amd) #REQUIRED
    modele CDATA #REQUIRED
>

<!-- dÃ©finition de l'Ã©lÃ©ment ram -->
<!ELEMENT ram EMPTY>
<!ATTLIST ram taille CDATA #REQUIRED>

<!-- definition de l'élément disque -->
<!ELEMENT disque EMPTY>
<!ATTLIST disque 
    taille CDATA #REQUIRED
    date CDATA #IMPLIED
    type (SSD | HD) "HD"
>

=== Makintoshe/Web-des-Donn-es/ValidationXML_DTD_XSD/ordinateurs_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ordinateurs SYSTEM "ordinateurs.dtd">
<ordinateurs>

    <ordinateur numero="pc_salon">
        <description marque="asus" ></description>
        <cpu marque="intel" modele="i5" />
        <ram taille="10Go"></ram>
        <disque taille ="250Go"></disque>
    </ordinateur>

    <ordinateur numero="pc_chambre" prix="50$">
        <description marque="asus">PC de la chambre</description>
        <cpu marque="intel" modele="i7"/>
        <ram taille="5Go"></ram>
        <disque taille="500Go" date="2021-10-08"></disque>
    </ordinateur>

</ordinateurs>
