=== Makintoshe/Web-des-Donn-es/ValidationXML_DTD_XSD/ordinateurs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="ordinateurs" type="ElemOrdinateurs"/>

  <xsd:complexType name="ElemOrdinateurs">
    <xsd:sequence>
      <xsd:element name="ordinateur" type="ElemOrdinateur" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ElemOrdinateur">
    <xsd:sequence>
      <xsd:element name="description" type="ElemDescription"/>
      <xsd:element name="cpu" type="ElemCPU"/>
      <xsd:element name="ram" type="ElemRam"/>
      <xsd:element name="disque" type="ElemDisk"/>
    </xsd:sequence>
    <xsd:attribute name="numero" type="xsd:ID" use="required"/>
    <xsd:attribute name="prix" type="priceType" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="ElemDescription">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="marque" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="ElemCPU">
    <xsd:attribute name="marque" type="xsd:string" use="required"/>
    <xsd:attribute name="modele" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="ElemRam"> 
    <xsd:attribute name="taille" type="xsd:string"/>
</xsd:complexType>

  <xsd:complexType name="ElemDisk">
    <xsd:attribute name="taille" type="xsd:string" />
    <xsd:attribute name="date" type="typeFormatDate" />
  </xsd:complexType>

  <xsd:simpleType name="typeFormatDate">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-9]{2}\/[0-9]{2}\/[0-9]{4}"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="priceType">
    <xsd:restriction base="xsd:decimal">
      <xsd:fractionDigits value="2"></xsd:fractionDigits>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== Makintoshe/Web-des-Donn-es/ValidationXML_DTD_XSD/ordinateurs_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<ordinateurs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ordinateurs.xsd">

        <ordinateur numero="pc_salon" prix="45.87">
            <description marque="asus" ></description>
            <cpu marque="intel" modele="i5" />
            <ram taille="10Go"></ram>
            <disque taille ="250Go"></disque>
        </ordinateur>
    
        <ordinateur numero="pc_chambre" >
            <description marque="asus">PC de la chambre</description>
            <cpu marque="intel" modele="i7"/>
            <ram taille="5Go"></ram>
            <disque taille="500Go" date="10/01/1998"></disque>
        </ordinateur>
    
</ordinateurs>
